language: python
matrix:
  fast_finish: true
  include:
    - python:  '3.10.2'
      dist:  bionic
    - python:  '3.9'
    - python:  '3.8'
    - python:  '3.7.13'

# command to install dependencies
install:
  - pip install .[dev]
# command to run tests
script: nosetests --with-coverage --cover-erase --cover-package=ksql

after_success:
  - codecov
